### DISCUSSION TITLE
Codecov / Nondeterministic tests

### DISCUSSION THREAD

**Discussion by dreua** [pdfarranger/pdfarranger#995] [General]
It seems like we have some nondeterministic tests and that messes with codecov: For example I got a red from codecov/project in #994 which didn't touch coverage at all.

In order to mitigate this I tried relaxing the settings a bit to allow one line to change (the `if self.quit: return` is very likely just nondeterministic and it probably not worth it to add additional tests just to cover it all the time).

In https://app.codecov.io/account/gh/pdfarranger/yaml I set the default settings for the PDF Arranger organization as follows:

```yaml
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.04%
```

This was meant as just a quick test but I'd like to leave it like this (maybe even increase the threshold) and see how it works.

In a subsequent run I got even more line hits than previously so we might have an even bigger issue with nondeterminism than I originally thought.

**Comment by jeromerobert** [comment]
> (maybe even increase the threshold) and see how it works.

Yes ! It will remove false negative until someone find why they append.

> even bigger issue with nondeterminism than I originally thought

Yes. I had the feeling that codecov is sometime selecting a wrong base commit when doing a coverage diff. That's just a feeling, I did not investigated.

**Reply by dreua** [reply]
What I saw looked more like race conditions in our tests, maybe version changes in our dependencies. But it could be issues in codecov as well, idk.

**Reply by jeromerobert** [reply]
Hum may be that calling `codecov/codecov-action` in multiple GHA build is not a great idea. Let met try to call it only one time.

**Reply by jeromerobert** [reply]
https://about.codecov.io/blog/uploading-code-coverage-in-a-separate-job-on-github-actions/

**Comment by jeromerobert** [comment]
This should now be fixed (see https://github.com/pdfarranger/pdfarranger/pull/998)

**Reply by dreua** [reply]
Thank you!!

**Comment by jeromerobert** [comment]
I also added this to the YAML file:

```yaml
coverage:
  status:
    patch:
      default:
        informational: true
```

See https://docs.codecov.com/docs/commit-status#informational for details

**Reply by dreua** [reply]
Added that also to the project:
```yaml
    project:
      default:
        informational: true
```
